### ISSUE TITLE
highlighting is broken when function name contains reserved words like show/set/include

### ISSUE THREAD

**Issue by istudyatuni** [hyrious/typst-syntax-highlight#32]
1.

![image](https://github.com/hyrious/typst-syntax-highlight/assets/43654815/55570e84-e892-4a40-bd46-39ff35e7d51d)

<details><summary>code</summary>
<p>

```typ
#{
    let show-one() = []
    let order = [#show-one()]
    let mhm = "?"
    mhm
}
```

</p>
</details> 

2. also highlighting is incorrect when these words are used in variable name 

![image](https://github.com/hyrious/typst-syntax-highlight/assets/43654815/1c20321a-1e52-4463-82c1-7ed0545ea871)

<details><summary>code</summary>
<p>

```typ
#{
    let show-one = [asdf]
    show-one
}
```

</p>
</details>

**Comment by istudyatuni** [comment]
Seems like case 1 is broken because there is no linebreak before closing `]`
![image](https://github.com/hyrious/typst-syntax-highlight/assets/43654815/dca94b61-d8ad-4511-b021-3baaa12656f0)

**Comment by hyrious** [comment]
It seems tree-sitter (which GitHub uses to render the source code view) also cannot handle this case, haha..

Note that we cannot actually match a random "expression" in sublime syntax because that will be too complicated. We can fix some common cases but eventually it won't be a complete language parser.
